
###
POST https://cms-kit-sanity.vercel.app/api/roll-out
Content-Type: application/json

{
  "email": "regx@usul.su"
}

###

GET https://api.sanity.io/v2021-06-07/organizations
Content-Type: application/json
Authorization: Bearer sk2CbeaOBIwe8XwLwNt22Br2pCnW5G9eJrDUhnaXSL9Q8oXN6uyqCFwH2F0i3qd80v92KodPrxgJiOVTk

###

GET https://api.sanity.io/v2021-06-07/me
Content-Type: application/json
Authorization: Bearer sk2CbeaOBIwe8XwLwNt22Br2pCnW5G9eJrDUhnaXSL9Q8oXN6uyqCFwH2F0i3qd80v92KodPrxgJiOVTk


###

GET https://api.vercel.com/v2/teams
Content-Type: application/json
Authorization: Bearer 1PaMPA60lqRUfFebYQyU8thy
###

GET https://api.vercel.com/v2/user
Content-Type: application/json
Authorization: Bearer 1PaMPA60lqRUfFebYQyU8thy
