name: Demo Project Rollout Script

on:
  workflow_dispatch:
    inputs:
      email:
        required: false
        type: string
        description: user email

jobs:
  launch-cli-script:
    runs-on: ubuntu-latest
    name: Launch CLI script Automatically
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Rollout script
        run: pnpm run rollout:action
        env:
          EMAIL: ${{ github.event.inputs.email }}
          REPO_ID: ${{ github.event.repository.id }}
          REPO_PROD_BRANCH: ${{ github.ref }}
          REPO_NAME: ${{ github.repository }}
          REPO_TYPE: github
          PROJECT_PREFIX: ${{ secrets.PROJECT_PREFIX }}
          VERCEL_PERSONAL_AUTH_TOKEN: ${{ secrets.VERCEL_PERSONAL_AUTH_TOKEN }}
          SANITY_PERSONAL_AUTH_TOKEN: ${{ secrets.SANITY_PERSONAL_AUTH_TOKEN }}
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_PERSONAL_AUTH_TOKEN }}
          SANITY_ORGANIZATION_ID: ${{ secrets.SANITY_ORGANIZATION_ID }}
          VERCEL_FR_TEAM_ID: ${{ secrets.VERCEL_FR_TEAM_ID }}
          VERCEL_FR_TEAM_SLUG: ${{ secrets.VERCEL_FR_TEAM_SLUG }}
          PROJECT_NAME: ${{ github.event.repository.name }}
          NEXT_PUBLIC_SANITY_DATASET: production
          MAX_NUMBER_OF_PROJECTS: 50
