name: Demo Project Rollout Script

on:
  workflow_dispatch:
    inputs:
      email:
        required: true
        type: string
        description: user email

jobs:
  launch-cli-script:
    runs-on: ubuntu-latest
    name: Launch CLI script Automatically
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Rollout script
        run: pnpm run rollout:action
        env:
          EMAIL: ${{ github.event.inputs.email }}
          PROJECT_PREFIX: ${{ secrets.PROJECT_PREFIX }}
          VERCEL_PERSONAL_AUTH_TOKEN: ${{ secrets.VERCEL_PERSONAL_AUTH_TOKEN }}
          SANITY_PERSONAL_AUTH_TOKEN: ${{ secrets.SANITY_PERSONAL_AUTH_TOKEN }}
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_PERSONAL_AUTH_TOKEN }}
          SANITY_ORGANIZATION_ID: ${{ secrets.SANITY_ORGANIZATION_ID }}
          VERCEL_FR_TEAM_ID: ${{ secrets.VERCEL_FR_TEAM_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          MAX_NUMBER_OF_PROJECTS: ${{ secrets.MAX_NUMBER_OF_PROJECTS }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          ROLL_OUT_API_TOKEN: ${{ secrets.ROLL_OUT_API_TOKEN }}
          REPO_ID: ${{ secrets.REPO_ID }}
          REPO_PROD_BRANCH: ${{ secrets.REPO_PROD_BRANCH }}
          REPO_TYPE: ${{ secrets.REPO_TYPE }}
