name: Trigger on a new repository started

on:
  create:
    types: [repository]

jobs:
  init-rollout:
    runs-on: ubuntu-latest
    name: Steps to init auto rollout
    steps:
      - name: Trigger existing endpoint
        run: |
          curl -X POST "https://cms-kit-sanity.vercel.app/api/roll-out" \
          -H "Authorization: Bearer ${{ secrets.ROLL_OUT_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "email": "usulpro@gmail.com"
          }'
