name: Print Repository ID

on:
  push:
    branches:
      - develop

jobs:
  print_repo_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Repository ID
        run: |
          echo "Repository ID: ${{ github.event.repository.id }}"
